language: ruby
rvm:
- 2.2.5
env:
- DB=postgresql
script:
- bundle exec rake spec
before_script:
- ENV=test bundle exec rake db:create
- ENV=test bundle exec rake db:schema:load
addons:
  postgres 9.5
  code_climate:
    repo_token: ENV[code_climate]