language: ruby
rvm:
  - 2.2.5
env:
  - DB=postgresql
addons:
  postgresql: '9.4'
  code_climate:
    repo_token: CODECLIMATE_REPO_TOKEN
script:
  - bundle exec rake spec
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare